# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update angular

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn run ng update;
    - run: yarn run ng update @angular/core @angular/cli @angular/material @angular/localize;
    - run: git config user.name "Team Kushal";
      if: always()
    - run: git config user.email "kus@tilde.team";
      if: always()
    - run: git add .;
      if: always()
    - run: git commit -m "update angular" -m "angular {cli, material, localize}";
      if: always()
    - run: git pull --rebase --strategy-option=theirs;
      if: always()
    - run: git push origin development;
      if: always()
